p8105\_hw2\_sal2222
================
Stephen Lewandowski
October 4, 2018

-   [Problem 1](#problem-1)
-   [Problem 2](#problem-2)
-   [Problem 3](#problem-3)

Problem 1
=========

First, I will read and clean the NYC Transit data.

``` r
nyc_subway_data <- read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>%
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, 
         entrance_type, ada) %>% 
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE)) 
 
nyc_subway_data
```

    ## # A tibble: 1,868 x 19
    ##    line  station_name station_latitude station_longitu~ route1 route2
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr> 
    ##  1 4 Av~ 25th St                  40.7            -74.0 R      <NA>  
    ##  2 4 Av~ 25th St                  40.7            -74.0 R      <NA>  
    ##  3 4 Av~ 36th St                  40.7            -74.0 N      R     
    ##  4 4 Av~ 36th St                  40.7            -74.0 N      R     
    ##  5 4 Av~ 36th St                  40.7            -74.0 N      R     
    ##  6 4 Av~ 45th St                  40.6            -74.0 R      <NA>  
    ##  7 4 Av~ 45th St                  40.6            -74.0 R      <NA>  
    ##  8 4 Av~ 45th St                  40.6            -74.0 R      <NA>  
    ##  9 4 Av~ 45th St                  40.6            -74.0 R      <NA>  
    ## 10 4 Av~ 53rd St                  40.6            -74.0 R      <NA>  
    ## # ... with 1,858 more rows, and 13 more variables: route3 <chr>,
    ## #   route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>, route8 <int>,
    ## #   route9 <int>, route10 <int>, route11 <int>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

This datase contains information related to each entrance and exit for each subway station in New York City, including the subway line, station name, location grid coordinates, routes served, entrance type, and ADA compliance status. My data cleaning steps so far have been to standardize variable names in "snake\_case", select and retain my variables of interest, and to recode the entry variable from a character class with "YES" or "NO" values to a logical class with "TRUE" or "FALSE" values. My resulting dataset has **1868 rows** and **19 columns**. These data are **not tidy** at this stage. The multiple columns for route numbers (routes 1 through 11) represent values themselves rather than a variable name.

I will answer specific questions using these data.

*How many distinct stations are there?*

There are **465** distinct stations, identified by both line and station name.

*How many stations are ADA compliant?*

``` r
nyc_subway_data %>% 
  filter(ada == TRUE) %>% 
  distinct(line, station_name) %>% 
  nrow()
```

    ## [1] 84

Of the 465 distinct stations, **84** have at least one ADA compliant entrance or exit.

*What proportion of station entrances / exits without vending allow entrance?*

``` r
{
  nyc_subway_data %>% 
  filter(vending == "NO") %>%
  filter(entry == TRUE) %>%  
  nrow()
} /
{
  nyc_subway_data %>% 
  filter(vending == "NO") %>%
  nrow()
}
```

    ## [1] 0.3770492

**0.37.7** (37.7%) of station entrances / exits without vending allow entrance. There are 183 entrances / exits without vending, and 69 of these allow entry.

I will now reformat the data so that route number and route name are distinct variables.

``` r
nyc_subway_data <- nyc_subway_data %>% 
  gather(key = route_number, value = route_name, route1:route11) 

nyc_subway_data
```

    ## # A tibble: 20,548 x 10
    ##    line  station_name station_latitude station_longitu~ entry vending
    ##    <chr> <chr>                   <dbl>            <dbl> <lgl> <chr>  
    ##  1 4 Av~ 25th St                  40.7            -74.0 TRUE  YES    
    ##  2 4 Av~ 25th St                  40.7            -74.0 TRUE  YES    
    ##  3 4 Av~ 36th St                  40.7            -74.0 TRUE  YES    
    ##  4 4 Av~ 36th St                  40.7            -74.0 TRUE  YES    
    ##  5 4 Av~ 36th St                  40.7            -74.0 TRUE  YES    
    ##  6 4 Av~ 45th St                  40.6            -74.0 TRUE  YES    
    ##  7 4 Av~ 45th St                  40.6            -74.0 TRUE  YES    
    ##  8 4 Av~ 45th St                  40.6            -74.0 TRUE  YES    
    ##  9 4 Av~ 45th St                  40.6            -74.0 TRUE  YES    
    ## 10 4 Av~ 53rd St                  40.6            -74.0 TRUE  YES    
    ## # ... with 20,538 more rows, and 4 more variables: entrance_type <chr>,
    ## #   ada <lgl>, route_number <chr>, route_name <chr>

*How many distinct stations serve the A train?*

``` r
nyc_subway_data %>% 
  filter(route_name == "A") %>% 
  distinct(line, station_name) %>% 
  nrow()
```

    ## [1] 60

**60** distinct stations serve the A train.

*How many are ADA compliant?*

``` r
nyc_subway_data %>% 
  filter(ada == TRUE) %>%  
  filter(route_name == "A") %>% 
  distinct(line, station_name) %>% 
  nrow()
```

    ## [1] 17

Of the 60 stations that serve the A train, **17** have at least one ADA compliant entry or exit.

Problem 2
=========

Problem 3
=========
